# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6e64aa15e4f7930fbad4a3cee5281a35f9d29591548a87b354156ef1f53b5b23fb95903e5edea43bd0fae3ac23a80794e4561b344d8bef8d27f22e4783251b

test:
  secret_key_base: 344b967a65ad7b1849bba4d4584c54e4a443c6719959b93f86a4c8b973c9410b0316619d67f6eb9c47b1c118a07814036e72ee40dcbbdd776d4f953bd299532b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
